baseURL = 'http://linutti.com/'
languageCode = 'en-us'
title = 'linutti'
[module]
  [module.hugoVersion]
    extended=true
    min = "0.41.0"

[menu]
    [[menu.main]]
        name = 'home'
        pageRef = '/'
        weight = 10
    [[menu.main]]
        name = 'posts'
        pageRef = '/posts'
        weight = 20
    [[menu.main]]
        name = 'tags'
        pageRef = '/tags'
        weight = 30
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'modus-vivendi'
    tabWidth = 4
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false

[params]
  [params.meta]
    description = ""
    favicon = false
  [params.theme_config]
    appearance = ""
    back_home_text = ""
    date_format = "02.01.2006"
    show_description = true
  [params.editPost]
    URL = "https://github.com/linutti/linutti.com/blob/main/content"
    text = "SUGGEST CHANGES"
    append_file_path = true

[outputs]
    home = ["HTML", "RSS"]
